### PR TITLE
Add travis configuration file

### PR DESCRIPTION
**Pull request by szabgab**
Please also enable the repository here: https://travis-ci.org/

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Hi, thanks for this.

I'm going to hold it for a while as the module needs the "libsndfile" installed and I'm not sure how to do that.

**Comment by jonathanstowe** [comment]
Thanks, I've worked out how to install the dependencies now so let's see how this goes.

**Comment by jonathanstowe** [comment]
All good

https://travis-ci.org/jonathanstowe/Audio-Sndfile

**Comment by szabgab** [comment]
:cookie:

**Pull request merged**
